apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cni.projectcalico.org/containerID: 5cbe049b6104b291b0319474c3390de0cd4a5f86d86346181f6bbc15aa729d76
      cni.projectcalico.org/podIP: 10.233.105.184/32
      cni.projectcalico.org/podIPs: 10.233.105.184/32
    creationTimestamp: "2025-06-18T09:10:31Z"
    generateName: jenkins-ddf884d56-
    generation: 1
    labels:
      app: jenkins
      pod-template-hash: ddf884d56
    name: jenkins-ddf884d56-264g5
    namespace: jenkins
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: jenkins-ddf884d56
      uid: f0e3c848-378a-4f32-986a-91df80f3c8bb
    resourceVersion: "50507"
    uid: 8fb3d6e4-e5d0-444f-a2aa-b2d350d7bf74
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -Xmx2g
      image: jenkins/jenkins:2.440.3-lts-jdk17
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 90
        periodSeconds: 30
        successThreshold: 1
        timeoutSeconds: 10
      name: jenkins
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      - containerPort: 50000
        name: jnlp
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      resources:
        limits:
          cpu: "2"
          memory: 3Gi
        requests:
          cpu: 500m
          memory: 1Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/jenkins_home
        name: jenkins-home
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-pvmv6
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    initContainers:
    - command:
      - sh
      - -c
      - chown -R 1000:1000 /var/jenkins_home
      image: busybox
      imagePullPolicy: Always
      name: volume-permissions
      resources: {}
      securityContext:
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/jenkins_home
        name: jenkins-home
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-pvmv6
        readOnly: true
    nodeName: worker1
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    serviceAccount: jenkins-admin
    serviceAccountName: jenkins-admin
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: jenkins-home
      persistentVolumeClaim:
        claimName: jenkins-pvc
    - name: kube-api-access-pvmv6
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-06-19T06:39:09Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-06-18T09:10:40Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-06-19T06:40:17Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-06-19T06:40:17Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-06-18T09:10:31Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 500m
        memory: 1Gi
      containerID: containerd://258554316970d59df928e55f63f3539f09879e061481c79c57538b0495d8b8c2
      image: docker.io/jenkins/jenkins:2.440.3-lts-jdk17
      imageID: docker.io/jenkins/jenkins@sha256:de4fea113221ab9e67567da3248abcb731dbe407056d0cab28cfa88bad9ae536
      lastState:
        terminated:
          containerID: containerd://a2c297337e11311598bd959812fab3fb8f11359cf8e67c155ccef7b41fd84702
          exitCode: 255
          finishedAt: "2025-06-19T06:22:58Z"
          reason: Unknown
          startedAt: "2025-06-19T01:56:15Z"
      name: jenkins
      ready: true
      resources:
        limits:
          cpu: "2"
          memory: 3Gi
        requests:
          cpu: 500m
          memory: 1Gi
      restartCount: 3
      started: true
      state:
        running:
          startedAt: "2025-06-19T06:39:12Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
          uid: 1000
      volumeMounts:
      - mountPath: /var/jenkins_home
        name: jenkins-home
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-pvmv6
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 192.168.122.93
    hostIPs:
    - ip: 192.168.122.93
    initContainerStatuses:
    - containerID: containerd://d168360225fb0abc92d7f4d25ab592fb160c01fa32682e5cefb11f50ad6574dd
      image: docker.io/library/busybox:latest
      imageID: docker.io/library/busybox@sha256:f85340bf132ae937d2c2a763b8335c9bab35d6e8293f70f606b9c6178d84f42b
      lastState: {}
      name: volume-permissions
      ready: true
      resources: {}
      restartCount: 3
      started: false
      state:
        terminated:
          containerID: containerd://d168360225fb0abc92d7f4d25ab592fb160c01fa32682e5cefb11f50ad6574dd
          exitCode: 0
          finishedAt: "2025-06-19T06:39:11Z"
          reason: Completed
          startedAt: "2025-06-19T06:39:09Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 10
          - 1000
          uid: 0
      volumeMounts:
      - mountPath: /var/jenkins_home
        name: jenkins-home
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-pvmv6
        readOnly: true
        recursiveReadOnly: Disabled
    phase: Running
    podIP: 10.233.105.184
    podIPs:
    - ip: 10.233.105.184
    qosClass: Burstable
    startTime: "2025-06-18T09:10:32Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"jenkins"},"name":"jenkins-service","namespace":"jenkins"},"spec":{"ports":[{"name":"http","nodePort":30999,"port":8080,"targetPort":8080},{"name":"jnlp","nodePort":30998,"port":50000,"targetPort":50000}],"selector":{"app":"jenkins"},"type":"NodePort"}}
    creationTimestamp: "2025-06-18T09:10:31Z"
    labels:
      app: jenkins
    name: jenkins-service
    namespace: jenkins
    resourceVersion: "23642"
    uid: aaeca23b-3f9b-4386-a8c8-0d026ded405a
  spec:
    clusterIP: 10.233.31.106
    clusterIPs:
    - 10.233.31.106
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30999
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jnlp
      nodePort: 30998
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: jenkins
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"jenkins"},"name":"jenkins","namespace":"jenkins"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jenkins"}},"template":{"metadata":{"labels":{"app":"jenkins"}},"spec":{"containers":[{"env":[{"name":"JAVA_OPTS","value":"-Xmx2g"}],"image":"jenkins/jenkins:2.440.3-lts-jdk17","livenessProbe":{"httpGet":{"path":"/login","port":8080},"initialDelaySeconds":90,"periodSeconds":30,"timeoutSeconds":10},"name":"jenkins","ports":[{"containerPort":8080,"name":"http"},{"containerPort":50000,"name":"jnlp"}],"readinessProbe":{"httpGet":{"path":"/login","port":8080},"initialDelaySeconds":60,"periodSeconds":10,"timeoutSeconds":5},"resources":{"limits":{"cpu":"2000m","memory":"3Gi"},"requests":{"cpu":"500m","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-home"}]}],"initContainers":[{"command":["sh","-c","chown -R 1000:1000 /var/jenkins_home"],"image":"busybox","name":"volume-permissions","securityContext":{"runAsUser":0},"volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-home"}]}],"securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsUser":1000},"serviceAccountName":"jenkins-admin","volumes":[{"name":"jenkins-home","persistentVolumeClaim":{"claimName":"jenkins-pvc"}}]}}}}
    creationTimestamp: "2025-06-18T09:10:31Z"
    generation: 1
    labels:
      app: jenkins
    name: jenkins
    namespace: jenkins
    resourceVersion: "50511"
    uid: 3020cc69-3add-4664-9850-a6328fa14fd0
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jenkins
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: jenkins
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: -Xmx2g
          image: jenkins/jenkins:2.440.3-lts-jdk17
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: jenkins
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 50000
            name: jnlp
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
        dnsPolicy: ClusterFirst
        initContainers:
        - command:
          - sh
          - -c
          - chown -R 1000:1000 /var/jenkins_home
          image: busybox
          imagePullPolicy: Always
          name: volume-permissions
          resources: {}
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
        serviceAccount: jenkins-admin
        serviceAccountName: jenkins-admin
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-06-18T09:10:31Z"
      lastUpdateTime: "2025-06-18T09:11:45Z"
      message: ReplicaSet "jenkins-ddf884d56" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-06-19T06:40:17Z"
      lastUpdateTime: "2025-06-19T06:40:17Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-06-18T09:10:31Z"
    generation: 1
    labels:
      app: jenkins
      pod-template-hash: ddf884d56
    name: jenkins-ddf884d56
    namespace: jenkins
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: jenkins
      uid: 3020cc69-3add-4664-9850-a6328fa14fd0
    resourceVersion: "50510"
    uid: f0e3c848-378a-4f32-986a-91df80f3c8bb
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jenkins
        pod-template-hash: ddf884d56
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: jenkins
          pod-template-hash: ddf884d56
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: -Xmx2g
          image: jenkins/jenkins:2.440.3-lts-jdk17
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: jenkins
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 50000
            name: jnlp
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
        dnsPolicy: ClusterFirst
        initContainers:
        - command:
          - sh
          - -c
          - chown -R 1000:1000 /var/jenkins_home
          image: busybox
          imagePullPolicy: Always
          name: volume-permissions
          resources: {}
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
        serviceAccount: jenkins-admin
        serviceAccountName: jenkins-admin
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
